# Generated by Django 5.2.17 on 2026-09-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(choices=[('CBC', 'Complete Blood Count'), ('BLOOD_GLUCOSE', 'Blood Glucose'), ('LIPID_PROFILE', 'Lipid Profile'), ('HBA1C', 'HbA1c'), ('KFT', 'Kidney Function Test'), ('LFT', 'Liver Function Test'), ('TFT', 'Thyroid Function Test'), ('URINALYSIS', 'Urinalysis')], max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('assigned_lab_tech', models.ForeignKey(blank=True, help_text='Null until a lab tech claims it - see LabTestClaimView.', limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_assigned', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_text', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_recorded', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='labtests.labtestrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
