# Generated by Django 5.2.17 on 2026-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresult',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='ai_numeric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='ai_reference_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='ai_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unavailable', 'Unavailable')], max_length=15),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='ai_status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ELEVATED', 'Elevated'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], max_length=10),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='ai_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
