# Generated by Django 5.2.17 on 2026-09-03 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('checkins', '0001_initial'),
        ('medications', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('caretaker', 'Caretaker')], max_length=10)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('alert', 'Doctor alert (high-risk check-in)'), ('checkin_result', "Patient's own check-in risk result"), ('caretaker_update', 'Caretaker check-in update'), ('medication_reminder', 'Medication reminder')], max_length=25)),
                ('subject', models.CharField(max_length=200)),
                ('risk_level', models.CharField(blank=True, max_length=15)),
                ('sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to='alerts.alert')),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to='checkins.dailycheckin')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_logs', to='patients.patient')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('medication_reminder', 'Medication reminder'), ('alert', 'Alert'), ('invitation', 'Invitation'), ('general', 'General')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
