# Generated by Django 5.2.17 on 2026-09-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationlog',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notification_logs', to='labtests.labtestrequest'),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='category',
            field=models.CharField(choices=[('alert', 'Doctor alert (high-risk check-in)'), ('checkin_result', "Patient's own check-in risk result"), ('caretaker_update', 'Caretaker check-in update'), ('medication_reminder', 'Medication reminder'), ('lab_test_request', 'New lab test request (lab technician alert)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='recipient_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('caretaker', 'Caretaker'), ('lab_tech', 'Lab Technician')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('medication_reminder', 'Medication reminder'), ('alert', 'Alert'), ('invitation', 'Invitation'), ('lab_test_request', 'New lab test request'), ('general', 'General')], max_length=25),
        ),
    ]
