# Generated by Django 5.2.17 on 2026-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailnotificationlog_lab_test_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationlog',
            name='category',
            field=models.CharField(choices=[('alert', 'Doctor alert (high-risk check-in)'), ('checkin_result', "Patient's own check-in risk result"), ('caretaker_update', 'Caretaker check-in update'), ('medication_reminder', 'Medication reminder'), ('lab_test_request', 'New lab test request (lab technician alert)'), ('lab_result_ready', 'Lab result ready for review (doctor alert)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('medication_reminder', 'Medication reminder'), ('alert', 'Alert'), ('invitation', 'Invitation'), ('lab_test_request', 'New lab test request'), ('lab_result_ready', 'Lab result ready for review'), ('general', 'General')], max_length=25),
        ),
    ]
