# Generated by Django 5.2.17 on 2026-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_emailnotificationlog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('medication_reminder', 'Medication reminder'), ('alert', 'Alert'), ('invitation', 'Invitation'), ('lab_test_request', 'New lab test request'), ('lab_result_ready', 'Lab result ready for review'), ('appointment', 'Appointment'), ('general', 'General')], max_length=25),
        ),
    ]
