# Generated by Django 5.2.17 on 2026-09-03 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. "500mg"', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('three_times_daily', 'Three times daily'), ('weekly', 'Weekly'), ('as_needed', 'As needed')], max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='e.g. "after food"')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank = ongoing', null=True)),
                ('reminder_times', models.JSONField(default=list, help_text='List of "HH:MM" 24h local times to send a reminder each active day, e.g. ["08:00", "20:00"]')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='medications.medication')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'constraints': [models.UniqueConstraint(fields=('medication', 'scheduled_for'), name='unique_medication_reminder_slot')],
            },
        ),
    ]
