from django.contrib.auth import get_user_model
from django.db import transaction
from django.utils import timezone
from drf_spectacular.utils import extend_schema
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken

from apps.core.permissions import IsDoctor

from .models import InvitationCode
from .serializers import (
    InvitationCodeGenerateSerializer,
    InvitationCodeSerializer,
    InvitationRedeemResponseSerializer,
    InvitationRedeemSerializer,
)

User = get_user_model()


@extend_schema(tags=["Invitations"], summary="List invitation codes generated by the logged-in doctor")
class InvitationListView(generics.ListAPIView):
    serializer_class = InvitationCodeSerializer
    permission_classes = [permissions.IsAuthenticated, IsDoctor]

    def get_queryset(self):
        return InvitationCode.objects.filter(doctor=self.request.user).select_related("patient")


@extend_schema(
    tags=["Invitations"],
    summary="Generate an invitation code for a patient (Doctor only)",
    request=InvitationCodeGenerateSerializer,
    responses=InvitationCodeSerializer,
)
class InvitationGenerateView(APIView):
    permission_classes = [permissions.IsAuthenticated, IsDoctor]

    def post(self, request):
        serializer = InvitationCodeGenerateSerializer(data=request.data, context={"request": request})
        serializer.is_valid(raise_exception=True)
        invitation = serializer.save()
        return Response(InvitationCodeSerializer(invitation).data, status=status.HTTP_201_CREATED)


@extend_schema(tags=["Invitations"], summary="Revoke an unused invitation code (Doctor only)", request=None, responses=InvitationCodeSerializer)
class InvitationRevokeView(APIView):
    permission_classes = [permissions.IsAuthenticated, IsDoctor]

    def post(self, request, pk):
        invitation = generics.get_object_or_404(InvitationCode, pk=pk, doctor=request.user)
        if invitation.is_used:
            return Response({"detail": "Cannot revoke a code that has already been used."},
                             status=status.HTTP_400_BAD_REQUEST)
        invitation.revoked = True
        invitation.save(update_fields=["revoked"])
        return Response(InvitationCodeSerializer(invitation).data)


@extend_schema(
    tags=["Invitations"],
    summary="Redeem an invitation code to create + link a Patient account",
    request=InvitationRedeemSerializer,
    responses=InvitationRedeemResponseSerializer,
)
class InvitationRedeemView(APIView):
    """Public endpoint: the patient does not have an account yet."""
    permission_classes = [permissions.AllowAny]

    @transaction.atomic
    def post(self, request):
        serializer = InvitationRedeemSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data

        invitation = InvitationCode.objects.select_for_update().get(code=data["code"].strip().upper())
        if not invitation.is_valid:
            return Response({"detail": "This invitation code is no longer valid."},
                             status=status.HTTP_400_BAD_REQUEST)

        user = User(
            email=data["email"],
            username=data["username"],
            role=User.Role.PATIENT,
        )
        user.set_password(data["password"])
        user.save()

        patient = invitation.patient
        patient.user = user
        patient.save(update_fields=["user"])

        invitation.used_at = timezone.now()
        invitation.save(update_fields=["used_at"])

        refresh = RefreshToken.for_user(user)
        return Response(
            {
                "detail": "Account created and linked to doctor.",
                "access": str(refresh.access_token),
                "refresh": str(refresh),
                "patient_id": patient.id,
            },
            status=status.HTTP_201_CREATED,
        )
