# Generated by Django 5.2.17 on 2026-09-03 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('caretaker_name', models.CharField(blank=True, max_length=150, null=True)),
                ('caretaker_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invitation_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invitation_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patients', to='accounts.doctor')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
