// Single place to edit endpoint paths so they match the real backend.
export const ENDPOINTS = {
  AUTH_LOGIN: "/auth/login/",
  AUTH_ME: "/auth/me/",
  PATIENTS: "/patients/",
  PATIENT_BY_ID: (id) => `/patients/${id}/`,
  PATIENT_ME: "/patients/me/",
  INVITATIONS: "/invitations/generate/",
  INVITATIONS_VERIFY: "/invitations/redeem/",
  CHECKINS: "/checkins/",
  CHECKIN_BY_ID: (id) => `/checkins/${id}/`,
  CHECKINS_BY_PATIENT: (id) => `/checkins/?patient=${id}`,
  MEDICATIONS: "/medications/",
  MEDICATIONS_BY_PATIENT: (id) => `/medications/?patient=${id}`,
  MEDICATION_REMINDERS: (medicationId) => `/medications/${medicationId}/reminders/`,
  MEDICATION_REMINDERS_ACKNOWLEDGE: (id) => `/medications/reminders/${id}/acknowledge/`,
  ALERTS: "/alerts/",
  ALERT_RESOLVE: (id) => `/alerts/${id}/resolve/`,
  ANALYTICS_PATIENT: (id) => `/analytics/patients/${id}/`,
  ANALYTICS_DOCTOR: "/analytics/me/",
  AI_SUMMARY_PATIENT: "/analytics/me/ai-summary/",
  AI_SUMMARY_DOCTOR: (patientId) => `/analytics/patients/${patientId}/ai-summary/`,
  APPOINTMENTS: "/appointments/",
  APPOINTMENT_CONFIRM: (id) => `/appointments/${id}/confirm/`,
  APPOINTMENT_CANCEL: (id) => `/appointments/${id}/cancel/`,
  QR_GENERATE: "/qr/generate/",
  QR_VERIFY: "/qr/verify/",
  NOTIFICATIONS: "/notifications/",
  NOTIFICATIONS_UNREAD: "/notifications/?unread=true",
  NOTIFICATION_READ: (id) => `/notifications/${id}/read/`,
};
