# Generated by Django 5.2.17 on 2026-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('receptionist', 'Receptionist'), ('lab_tech', 'Lab Technician')], max_length=15),
        ),
    ]
