"""QR token generation/verification.

Default (approved) design: a short-lived signed JWT identifying one patient,
generated by the patient, shown as a QR code by the frontend, and verified
server-side when a doctor scans it. Signed with SIMPLE_JWT's signing key via
PyJWT directly (kept separate from login access/refresh tokens - this token
has a single narrow purpose and a much shorter lifetime).

Expiry default: settings.QR_TOKEN_EXPIRY_MINUTES (15 min).
"""
import jwt
from django.conf import settings
from django.utils import timezone

QR_TOKEN_TYPE = "patient_qr"


def generate_qr_token(patient) -> dict:
    now = timezone.now()
    expires_at = now + timezone.timedelta(minutes=settings.QR_TOKEN_EXPIRY_MINUTES)
    payload = {
        "type": QR_TOKEN_TYPE,
        "patient_id": patient.id,
        "iat": int(now.timestamp()),
        "exp": int(expires_at.timestamp()),
    }
    token = jwt.encode(payload, settings.SECRET_KEY, algorithm="HS256")
    return {"token": token, "expires_at": expires_at}


class InvalidQRToken(Exception):
    pass


def verify_qr_token(token: str) -> int:
    """Returns the patient_id if valid, else raises InvalidQRToken."""
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        raise InvalidQRToken("QR code has expired.")
    except jwt.InvalidTokenError:
        raise InvalidQRToken("QR code is invalid.")

    if payload.get("type") != QR_TOKEN_TYPE:
        raise InvalidQRToken("Not a valid patient QR token.")
    return payload["patient_id"]


def peek_patient_id_for_audit_log(token: str):
    """Best-effort patient_id extraction for AUDIT LOGGING ONLY when a token
    has expired - never use this for an authorization decision. The
    signature is still verified (so we know the token really was issued by
    this server for this patient); only the expiry check is skipped, so an
    expired-but-genuine scan can still be attributed to a patient in
    QRScanLog instead of logging a blank/unknown row.

    Returns None if the token isn't decodable at all (bad signature, wrong
    type, malformed) - those cases genuinely have no known patient to log.
    """
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"], options={"verify_exp": False})
    except jwt.InvalidTokenError:
        return None
    if payload.get("type") != QR_TOKEN_TYPE:
        return None
    return payload.get("patient_id")
