# Generated by Django 5.2.17 on 2026-09-04 00:02

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LAB_REPORT", "Laboratory Report"),
                            ("PRESCRIPTION", "Prescription Document"),
                            ("CONSULTATION", "Consultation Note"),
                            ("DISCHARGE_SUMMARY", "Discharge Summary"),
                            ("IMAGING_REPORT", "Imaging Report"),
                            ("OTHER", "Other Medical Document"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_file_path
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=100)),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing OCR / Vision"),
                            ("processed", "Processed & Indexed"),
                            ("failed", "Processing Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not Applicable"),
                            ("draft", "Draft Candidate Extraction"),
                            ("review_required", "Doctor Review Required"),
                            ("verified", "Doctor Verified & Approved"),
                            ("rejected", "Rejected by Doctor"),
                        ],
                        default="not_applicable",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured clinical extraction findings, confidence scores, and provenance metadata.",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_medical_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "document_type"],
                        name="documents_m_patient_558c2c_idx",
                    ),
                    models.Index(
                        fields=["patient", "processing_status"],
                        name="documents_m_patient_feed3e_idx",
                    ),
                ],
            },
        ),
    ]
