# Generated by Django 5.2.17 on 2026-09-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='extraction_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('draft', 'Draft Candidate Extraction'), ('review_required', 'Doctor Review Required'), ('completed', 'Extraction Completed'), ('verified', 'Doctor Verified & Approved'), ('rejected', 'Rejected by Doctor')], default='not_applicable', max_length=20),
        ),
    ]
