# Generated by Django 5.2.17 on 2026-09-04 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_medicaldocument_extraction_status'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page', models.PositiveIntegerField(blank=True, help_text='Source page number, when the extraction pipeline tracks pages. Null when not available - never fabricated.', null=True)),
                ('document_type', models.CharField(help_text='Denormalized from document.document_type at index time.', max_length=30)),
                ('document_title', models.CharField(help_text='Denormalized from document.title at index time.', max_length=255)),
                ('document_date', models.DateTimeField(help_text='Denormalized from document.created_at (or an extracted document date, when confidently parsed) at index time.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.medicaldocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='patients.patient')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['patient', 'document'], name='documents_d_patient_17b887_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_chunk_per_document_index')],
            },
        ),
    ]
