# Generated by Django 5.2.17 on 2026-09-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('symptoms', models.TextField(blank=True)),
                ('severity_score', models.IntegerField(blank=True, null=True)),
                ('duration', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_risk_level', models.TextField(blank=True, null=True)),
                ('ai_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_reason', models.TextField(blank=True, null=True)),
                ('ai_recommended_action', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='patients.patient')),
            ],
            options={
                'ordering': ['-checkin_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'checkin_date'), name='unique_patient_checkin_per_day')],
            },
        ),
    ]
