# Generated by Django 5.2.17 on 2026-09-03 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField(help_text='Calendar date this check-in is for (patient-local).')),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptom strings selected by patient.')),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, help_text='0-10 self-reported scale.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=dict, help_text='e.g. {"temperature_c": 37.2, "heart_rate": 78}')),
                ('ai_risk_level', models.CharField(choices=[('pending', 'Pending AI analysis'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unavailable', 'AI engine unavailable')], default='pending', max_length=15)),
                ('ai_risk_score', models.FloatField(blank=True, help_text="AI engine's riskScore, 0.0-1.0.", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_notes', models.TextField(blank=True, help_text="AI engine's 'reason' text.")),
                ('ai_recommended_action', models.TextField(blank=True, help_text="AI engine's 'recommendedAction'.")),
                ('ai_notification_recipient', models.CharField(blank=True, help_text="AI engine's suggested recipient - informational only, NOT used for routing (the backend decides routing via apps.alerts.rules based on ai_risk_level).", max_length=30)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='patients.patient')),
            ],
            options={
                'ordering': ['-checkin_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'checkin_date'), name='unique_patient_checkin_per_day')],
            },
        ),
    ]
