# Generated by Django 5.2.17 on 2026-09-04 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='checkin_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Calendar date this check-in is for (patient-local).'),
        ),
    ]
