# Generated by Django 5.2.17 on 2026-09-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscanlog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scan_logs', to='patients.patient'),
        ),
    ]
