# Generated by Django 5.2.17 on 2026-09-04 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('qr', '0002_alter_qrscanlog_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('purpose', models.CharField(default='qr_scan_consultation', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_access_grants', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_access_grants', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'doctor', 'expires_at'], name='qr_qraccess_patient_0d33af_idx')],
            },
        ),
    ]
